import type { Product } from "@/types";

const now = new Date().toISOString();

export const mockProducts: Product[] = [
  {
    id: "clothing-1",
    slug: "urban-oversized-tee-black",
    name: "Urban Oversized Tee",
    description:
      "Premium cotton oversized t-shirt with a relaxed silhouette and soft hand feel for everyday wear.",
    price: 39,
    originalPrice: 49,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/urban-oversized-tee-black-1/800/800",
      "https://picsum.photos/seed/urban-oversized-tee-black-2/800/800",
      "https://picsum.photos/seed/urban-oversized-tee-black-3/800/800",
    ],
    colors: ["black", "white", "gray"],
    sizes: ["S", "M", "L", "XL"],
    stock: 18,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.5,
    reviewCount: 124,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-2",
    slug: "minimal-linen-shirt-ivory",
    name: "Minimal Linen Shirt",
    description:
      "Lightweight linen shirt tailored for warm-weather styling with a clean modern cut.",
    price: 69,
    originalPrice: null,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/minimal-linen-shirt-ivory-1/800/800",
      "https://picsum.photos/seed/minimal-linen-shirt-ivory-2/800/800",
      "https://picsum.photos/seed/minimal-linen-shirt-ivory-3/800/800",
    ],
    colors: ["ivory", "beige", "navy"],
    sizes: ["S", "M", "L"],
    stock: 10,
    isOnSale: false,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 88,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-3",
    slug: "tailored-wide-leg-trousers",
    name: "Tailored Wide-Leg Trousers",
    description:
      "Elegant wide-leg trousers with structured drape for polished day-to-night outfits.",
    price: 89,
    originalPrice: 119,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/tailored-wide-leg-trousers-1/800/800",
      "https://picsum.photos/seed/tailored-wide-leg-trousers-2/800/800",
      "https://picsum.photos/seed/tailored-wide-leg-trousers-3/800/800",
    ],
    colors: ["charcoal", "black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 7,
    isOnSale: true,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.4,
    reviewCount: 62,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-4",
    slug: "soft-knit-cardigan-burgundy",
    name: "Soft Knit Cardigan",
    description:
      "Cozy rib-knit cardigan in a rich burgundy tone, ideal for layering through the season.",
    price: 79,
    originalPrice: null,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/soft-knit-cardigan-burgundy-1/800/800",
      "https://picsum.photos/seed/soft-knit-cardigan-burgundy-2/800/800",
      "https://picsum.photos/seed/soft-knit-cardigan-burgundy-3/800/800",
    ],
    colors: ["burgundy", "cream"],
    sizes: ["M", "L", "XL"],
    stock: 12,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 49,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-5",
    slug: "structured-denim-jacket",
    name: "Structured Denim Jacket",
    description:
      "Modern denim jacket with refined seams and a structured silhouette for effortless layering.",
    price: 99,
    originalPrice: 129,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/structured-denim-jacket-1/800/800",
      "https://picsum.photos/seed/structured-denim-jacket-2/800/800",
      "https://picsum.photos/seed/structured-denim-jacket-3/800/800",
    ],
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 5,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 203,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-6",
    slug: "everyday-jogger-pants",
    name: "Everyday Jogger Pants",
    description:
      "Tapered joggers in stretch fabric with soft lining for elevated comfort.",
    price: 59,
    originalPrice: null,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/everyday-jogger-pants-1/800/800",
      "https://picsum.photos/seed/everyday-jogger-pants-2/800/800",
      "https://picsum.photos/seed/everyday-jogger-pants-3/800/800",
    ],
    colors: ["gray", "black", "olive"],
    sizes: ["S", "M", "L", "XL"],
    stock: 22,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.3,
    reviewCount: 71,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-7",
    slug: "silk-blend-midi-dress",
    name: "Silk-Blend Midi Dress",
    description:
      "Flowing midi dress in a luxe silk blend with a flattering drape and subtle sheen.",
    price: 149,
    originalPrice: 189,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/silk-blend-midi-dress-1/800/800",
      "https://picsum.photos/seed/silk-blend-midi-dress-2/800/800",
      "https://picsum.photos/seed/silk-blend-midi-dress-3/800/800",
    ],
    colors: ["wine", "black", "emerald"],
    sizes: ["S", "M", "L"],
    stock: 4,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 157,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clothing-8",
    slug: "cotton-hoodie-essential",
    name: "Cotton Hoodie Essential",
    description:
      "Heavyweight cotton hoodie with brushed interior and a clean minimal finish.",
    price: 75,
    originalPrice: null,
    category: "CLOTHING",
    images: [
      "https://picsum.photos/seed/cotton-hoodie-essential-1/800/800",
      "https://picsum.photos/seed/cotton-hoodie-essential-2/800/800",
      "https://picsum.photos/seed/cotton-hoodie-essential-3/800/800",
    ],
    colors: ["black", "sand", "stone"],
    sizes: ["S", "M", "L", "XL"],
    stock: 16,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.4,
    reviewCount: 96,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-1",
    slug: "retro-runner-sneakers",
    name: "Retro Runner Sneakers",
    description:
      "Retro-inspired runners with cushioned support and street-ready styling.",
    price: 119,
    originalPrice: 149,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/retro-runner-sneakers-1/800/800",
      "https://picsum.photos/seed/retro-runner-sneakers-2/800/800",
      "https://picsum.photos/seed/retro-runner-sneakers-3/800/800",
    ],
    colors: ["white", "red", "black"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    stock: 15,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.7,
    reviewCount: 181,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-2",
    slug: "leather-loafers-classic",
    name: "Classic Leather Loafers",
    description:
      "Polished leather loafers with a comfortable insole and timeless silhouette.",
    price: 159,
    originalPrice: null,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/leather-loafers-classic-1/800/800",
      "https://picsum.photos/seed/leather-loafers-classic-2/800/800",
      "https://picsum.photos/seed/leather-loafers-classic-3/800/800",
    ],
    colors: ["brown", "black"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 9,
    isOnSale: false,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.6,
    reviewCount: 74,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-3",
    slug: "cloud-walk-slip-ons",
    name: "Cloud Walk Slip-Ons",
    description:
      "Ultra-light slip-ons with breathable knit upper and flexible outsole.",
    price: 79,
    originalPrice: 99,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/cloud-walk-slip-ons-1/800/800",
      "https://picsum.photos/seed/cloud-walk-slip-ons-2/800/800",
      "https://picsum.photos/seed/cloud-walk-slip-ons-3/800/800",
    ],
    colors: ["gray", "navy", "white"],
    sizes: ["38", "39", "40", "41", "42"],
    stock: 20,
    isOnSale: true,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.2,
    reviewCount: 52,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-4",
    slug: "high-top-canvas-redline",
    name: "High-Top Canvas Redline",
    description:
      "Iconic canvas high-tops finished with bold red accent stitching.",
    price: 89,
    originalPrice: null,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/high-top-canvas-redline-1/800/800",
      "https://picsum.photos/seed/high-top-canvas-redline-2/800/800",
      "https://picsum.photos/seed/high-top-canvas-redline-3/800/800",
    ],
    colors: ["black", "red", "white"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 13,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.3,
    reviewCount: 67,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-5",
    slug: "performance-training-shoes",
    name: "Performance Training Shoes",
    description:
      "Supportive training shoes with responsive cushioning for high-energy sessions.",
    price: 129,
    originalPrice: 169,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/performance-training-shoes-1/800/800",
      "https://picsum.photos/seed/performance-training-shoes-2/800/800",
      "https://picsum.photos/seed/performance-training-shoes-3/800/800",
    ],
    colors: ["black", "lime", "white"],
    sizes: ["40", "41", "42", "43", "44", "45"],
    stock: 6,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.8,
    reviewCount: 143,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-6",
    slug: "elegant-pointed-heels",
    name: "Elegant Pointed Heels",
    description:
      "Sleek pointed heels with a timeless shape and comfortable padded footbed.",
    price: 139,
    originalPrice: null,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/elegant-pointed-heels-1/800/800",
      "https://picsum.photos/seed/elegant-pointed-heels-2/800/800",
      "https://picsum.photos/seed/elegant-pointed-heels-3/800/800",
    ],
    colors: ["black", "nude", "red"],
    sizes: ["36", "37", "38", "39", "40"],
    stock: 11,
    isOnSale: false,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.5,
    reviewCount: 98,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-7",
    slug: "trail-hiker-boots",
    name: "Trail Hiker Boots",
    description:
      "Durable hiking boots with a grippy outsole and weather-ready upper.",
    price: 199,
    originalPrice: 249,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/trail-hiker-boots-1/800/800",
      "https://picsum.photos/seed/trail-hiker-boots-2/800/800",
      "https://picsum.photos/seed/trail-hiker-boots-3/800/800",
    ],
    colors: ["tan", "brown", "black"],
    sizes: ["40", "41", "42", "43", "44"],
    stock: 3,
    isOnSale: true,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.9,
    reviewCount: 116,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shoes-8",
    slug: "minimalist-sandals",
    name: "Minimalist Leather Sandals",
    description: "Minimal sandals in soft leather with a clean modern profile.",
    price: 69,
    originalPrice: null,
    category: "SHOES",
    images: [
      "https://picsum.photos/seed/minimalist-sandals-1/800/800",
      "https://picsum.photos/seed/minimalist-sandals-2/800/800",
      "https://picsum.photos/seed/minimalist-sandals-3/800/800",
    ],
    colors: ["tan", "black", "white"],
    sizes: ["37", "38", "39", "40", "41"],
    stock: 14,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.1,
    reviewCount: 35,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-1",
    slug: "metro-crossbody-bag",
    name: "Metro Crossbody Bag",
    description:
      "Compact crossbody bag with organized compartments and a versatile adjustable strap.",
    price: 89,
    originalPrice: 119,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/metro-crossbody-bag-1/800/800",
      "https://picsum.photos/seed/metro-crossbody-bag-2/800/800",
      "https://picsum.photos/seed/metro-crossbody-bag-3/800/800",
    ],
    colors: ["black", "olive", "tan"],
    sizes: ["One Size"],
    stock: 17,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.6,
    reviewCount: 129,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-2",
    slug: "structured-tote-signature",
    name: "Signature Structured Tote",
    description:
      "Spacious structured tote with an internal pouch for polished daily carry.",
    price: 149,
    originalPrice: null,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/structured-tote-signature-1/800/800",
      "https://picsum.photos/seed/structured-tote-signature-2/800/800",
      "https://picsum.photos/seed/structured-tote-signature-3/800/800",
    ],
    colors: ["black", "taupe", "cream"],
    sizes: ["One Size"],
    stock: 8,
    isOnSale: false,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 84,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-3",
    slug: "weekender-duffle-pro",
    name: "Weekender Duffle Pro",
    description:
      "Travel-ready duffle bag with smart compartments and a durable finish.",
    price: 179,
    originalPrice: 229,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/weekender-duffle-pro-1/800/800",
      "https://picsum.photos/seed/weekender-duffle-pro-2/800/800",
      "https://picsum.photos/seed/weekender-duffle-pro-3/800/800",
    ],
    colors: ["navy", "black", "gray"],
    sizes: ["One Size"],
    stock: 6,
    isOnSale: true,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.7,
    reviewCount: 53,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-4",
    slug: "mini-bucket-bag-luxe",
    name: "Luxe Mini Bucket Bag",
    description:
      "Compact bucket bag with a premium textured finish and soft structure.",
    price: 99,
    originalPrice: null,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/mini-bucket-bag-luxe-1/800/800",
      "https://picsum.photos/seed/mini-bucket-bag-luxe-2/800/800",
      "https://picsum.photos/seed/mini-bucket-bag-luxe-3/800/800",
    ],
    colors: ["wine", "black", "camel"],
    sizes: ["One Size"],
    stock: 12,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.4,
    reviewCount: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-5",
    slug: "commuter-backpack-tech",
    name: "Commuter Tech Backpack",
    description:
      "Minimal backpack with a padded laptop sleeve and sleek commuter-focused design.",
    price: 129,
    originalPrice: 159,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/commuter-backpack-tech-1/800/800",
      "https://picsum.photos/seed/commuter-backpack-tech-2/800/800",
      "https://picsum.photos/seed/commuter-backpack-tech-3/800/800",
    ],
    colors: ["black", "gray", "navy"],
    sizes: ["One Size"],
    stock: 14,
    isOnSale: true,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.5,
    reviewCount: 92,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-6",
    slug: "chain-shoulder-bag-rouge",
    name: "Rouge Chain Shoulder Bag",
    description:
      "Elegant shoulder bag with a chain strap and softly quilted texture.",
    price: 169,
    originalPrice: null,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/chain-shoulder-bag-rouge-1/800/800",
      "https://picsum.photos/seed/chain-shoulder-bag-rouge-2/800/800",
      "https://picsum.photos/seed/chain-shoulder-bag-rouge-3/800/800",
    ],
    colors: ["red", "black", "ivory"],
    sizes: ["One Size"],
    stock: 9,
    isOnSale: false,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 77,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-7",
    slug: "canvas-shopper-everyday",
    name: "Everyday Canvas Shopper",
    description:
      "Durable canvas shopper with a roomy interior for everyday essentials.",
    price: 59,
    originalPrice: 79,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/canvas-shopper-everyday-1/800/800",
      "https://picsum.photos/seed/canvas-shopper-everyday-2/800/800",
      "https://picsum.photos/seed/canvas-shopper-everyday-3/800/800",
    ],
    colors: ["natural", "black", "olive"],
    sizes: ["One Size"],
    stock: 19,
    isOnSale: true,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.2,
    reviewCount: 58,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bags-8",
    slug: "travel-sling-compact",
    name: "Compact Travel Sling",
    description:
      "Hands-free sling bag with secure zip pockets and an ergonomic fit.",
    price: 49,
    originalPrice: null,
    category: "BAGS",
    images: [
      "https://picsum.photos/seed/travel-sling-compact-1/800/800",
      "https://picsum.photos/seed/travel-sling-compact-2/800/800",
      "https://picsum.photos/seed/travel-sling-compact-3/800/800",
    ],
    colors: ["black", "gray", "burgundy"],
    sizes: ["One Size"],
    stock: 21,
    isOnSale: false,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.1,
    reviewCount: 31,
    createdAt: now,
    updatedAt: now,
  },
];
